
function bindNextLevelFeatures(){
  const formatMoney=n=>'₹'+Math.round(Number(n)||0).toLocaleString('en-IN');
  const scenarios={
    'first-home':['First home','Start with monthly comfort and property readiness.','For a first purchase, begin with the monthly number you can carry, the contribution you expect to make, and the documents that make the property financeable. Then move to lender comparison.'],
    salaried:['Salaried','Make the income trail easy to explain.','Keep employment continuity, salary credits, existing obligations, and tax or bank records aligned before comparing lenders.'],
    'self-employed':['Self-employed','Translate the business story into a clear file.','Keep banking, tax records, business continuity, ownership, and personal obligations ready for a lender conversation.'],
    construction:['Construction','Sequence the build before the funding.','Land, approvals, estimates, stage milestones, inspections, and release conditions should be discussed as one project.'],
    transfer:['Balance transfer','Compare the entire difference.','Review outstanding principal, remaining tenure, current rate, switching costs, new conditions, and the real repayment difference.']
  };
  document.querySelectorAll('[data-scenario]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.scenario-tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const s=scenarios[btn.dataset.scenario]||scenarios['first-home'];const panel=document.querySelector('[data-scenario-panel]');if(panel)panel.innerHTML='<span class="eyebrow" style="color:var(--blue)">'+s[0]+'</span><h3>'+s[1]+'</h3><p>'+s[2]+'</p><div class="scenario-grid"><span><b>01</b> Define the monthly picture</span><span><b>02</b> Prepare the profile file</span><span><b>03</b> Review property conditions</span><span><b>04</b> Compare the route</span></div><a class="button button-orange" href="eligibility.html">Start this route →</a>';}));
  const run=document.querySelector('[data-affordability-run]');
  if(run)run.addEventListener('click',()=>{const income=+document.querySelector('#aff-income').value||0,ob=+document.querySelector('#aff-obligations').value||0,con=+document.querySelector('#aff-contribution').value||0;const available=Math.max(0,income*.45-ob),emi=Math.round(available);const rate=.0835/12,months=240;const loan=emi?Math.round(emi*(Math.pow(1+rate,months)-1)/(rate*Math.pow(1+rate,months))):0;const el=document.querySelector('[data-affordability-amount]');if(el)el.textContent=formatMoney(loan);const e=document.querySelector('[data-affordability-emi]');if(e)e.textContent=formatMoney(emi);const r=document.querySelector('[data-affordability-ratio]');if(r)r.textContent=Math.max(0,Math.round((income-ob)/Math.max(1,income)*100))+'%';const c=document.querySelector('[data-affordability-copy]');if(c)c.textContent='This indicative planning range uses a 45% repayment ceiling and the current sample rate. Confirm the lender’s method before acting.';});
}


function bindSignalHeader(){const header=document.querySelector('.site-nav');if(!header)return;const sync=()=>header.classList.toggle('scrolled',window.scrollY>18);sync();window.addEventListener('scroll',sync,{passive:true});}

(()=>{const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];const money=n=>`₹${Math.round(Number(n)||0).toLocaleString("en-IN")}`;const store=(k,v)=>localStorage.setItem(k,JSON.stringify(v));const load=(k,d=[])=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d));const event=(name,data={})=>{const list=load("hlsp_events");list.push({event:name,data,time:new Date().toISOString(),path:location.pathname,referrer:document.referrer});store("hlsp_events",list.slice(-500))};
function navigation(){const toggle=$(".menu-toggle"),drawer=$(".mobile-drawer"),close=$(".drawer-close"),hide=()=>{drawer?.classList.remove("open");document.body.classList.remove("lock")};toggle?.addEventListener("click",()=>{drawer?.classList.add("open");document.body.classList.add("lock")});close?.addEventListener("click",hide);drawer?.addEventListener("click",e=>{if(e.target===drawer)hide()});document.addEventListener("keydown",e=>e.key==="Escape"&&hide());$$('a[href^="#"]').forEach(a=>a.addEventListener("click",e=>{const target=$(a.getAttribute("href"));if(target){e.preventDefault();target.scrollIntoView({behavior:"smooth",block:"start"});history.replaceState(null,"",a.getAttribute("href"))}}));const current=location.pathname.split("/").pop()||"index.html";$$('.nav-links a').forEach(a=>a.classList.toggle("active",(a.getAttribute("href")||"").split("#")[0]===current))}
function reveal(){const els=$$(".reveal");if(!("IntersectionObserver"in window)){els.forEach(x=>x.classList.add("visible"));return}const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("visible");io.unobserve(e.target)}}),{threshold:.08});els.forEach((x,i)=>{x.style.transitionDelay=`${Math.min(i*35,210)}ms`;io.observe(x)})}
function calculator(){ $$('[data-calculator]').forEach(g=>{const a=$("[data-calc=amount]",g),r=$("[data-calc=rate]",g),t=$("[data-calc=tenure]",g),emi=$("[data-output=emi]",g);if(!a||!r||!t||!emi)return;const run=()=>{const P=+a.value,R=+r.value/1200,N=+t.value*12,E=R?P*R*Math.pow(1+R,N)/(Math.pow(1+R,N)-1):P/N,T=E*N;emi.textContent=money(E);$("[data-output=principal]",g)?.replaceChildren(money(P));$("[data-output=interest]",g)?.replaceChildren(money(T-P));$("[data-output=total]",g)?.replaceChildren(money(T));$$('[data-value]',g).forEach(x=>x.textContent=x.dataset.value==="amount"?money(P):x.dataset.value==="rate"?`${r.value}%`:`${t.value} years`)};[a,r,t].forEach(x=>x.addEventListener("input",()=>{event("calculator_started");run();event("calculator_completed",{amount:a.value,rate:r.value,tenure:t.value})}));run()})}
function leadForms(){ $$(".js-lead-form").forEach(form=>form.addEventListener("submit",e=>{e.preventDefault();if(!form.checkValidity()){form.reportValidity();return}const data=Object.fromEntries(new FormData(form).entries());data.id=`HL-${Date.now().toString().slice(-7)}`;data.status="NEW";data.created=new Date().toISOString();data.source=new URLSearchParams(location.search).get("utm_source")||"direct";data.medium=new URLSearchParams(location.search).get("utm_medium")||"none";data.campaign=new URLSearchParams(location.search).get("utm_campaign")||"none";const leads=load("hlsp_leads");leads.push(data);store("hlsp_leads",leads);event("lead_created",{id:data.id});form.innerHTML=`<div class="success" role="status"><h3>Enquiry received.</h3><p>Your reference is <strong>${data.id}</strong>. The advisory desk can continue by phone or WhatsApp.</p><a class="button button-orange" href="https://wa.me/919839324536" target="_blank" rel="noopener">Continue on WhatsApp →</a></div>`}))}
function eligibility(){const f=$("[data-eligibility-form]"),out=$("[data-eligibility-result]");if(!f||!out)return;f.addEventListener("submit",e=>{e.preventDefault();if(!f.checkValidity()){f.reportValidity();return}const income=+$('[name=income]',f).value,existing=+$('[name=existing_emi]',f).value,years=+$('[name=tenure]',f).value||20,capacity=Math.max(0,income*.5-existing),rate=.085,N=years*12,amount=capacity*(1-Math.pow(1+rate/12,-N))/(rate/12);$('[data-eligibility-amount]',out).textContent=money(amount);$('[data-eligibility-emi]',out).textContent=money(capacity);$('[data-eligibility-band]',out).textContent=income>100000?"8.35% – 9.25%":"8.50% – 10.25%";out.classList.remove("hidden");event("eligibility_completed",{amount:Math.round(amount)});out.scrollIntoView({behavior:"smooth",block:"center"})})}
function matching(){const f=$("[data-matching-form]"),out=$("[data-matching-result]");if(!f||!out)return;f.addEventListener("submit",e=>{e.preventDefault();if(!f.checkValidity()){f.reportValidity();return}const income=+$('[name=income]',f).value,loan=+$('[name=loan_amount]',f).value,employment=$('[name=employment]',f).value,city=$('[name=city]',f).value;const score=(income>=50000?2:1)+(loan<=income*60?2:1)+(employment==="Salaried"?2:1);const label=score>=5?"Best Match":score>=3?"Good Match":"Possible Match";out.classList.remove("hidden");out.innerHTML=`<span class="eyebrow" style="color:var(--blue)">Indicative lender match</span><div class="result-big">${label}</div><p>Based on the information supplied for ${city}. This is not guaranteed approval.</p><div class="result-grid"><div class="result-stat"><b>${employment}</b><span>Employment</span></div><div class="result-stat"><b>${money(income)}</b><span>Monthly income</span></div><div class="result-stat"><b>${money(loan)}</b><span>Requested loan</span></div></div>`;event("comparison_completed",{label,city})})}
function transferTopup(){const f=$("[data-balance-form]");f?.addEventListener("input",()=>{const balance=+$('[name=outstanding]',f).value||0,current=+$('[name=current_rate]',f).value||0,next=+$('[name=new_rate]',f).value||8.5,months=(+$('[name=remaining_years]',f).value||15)*12;const emi=r=>{const m=r/1200;return m?balance*m*Math.pow(1+m,months)/(Math.pow(1+m,months)-1):balance/months};$('[data-transfer-emi]',f).textContent=money(emi(next));$('[data-transfer-saving]',f).textContent=money(Math.max(0,emi(current)-emi(next)));$('[data-transfer-total]',f).textContent=money(Math.max(0,emi(current)-emi(next))*months)});const t=$("[data-topup-form]");t?.addEventListener("input",()=>{const property=+$('[name=property_value]',t).value||0,balance=+$('[name=topup_outstanding]',t).value||0;$('[data-topup-result]',t).textContent=money(Math.max(0,property*.7-balance))})}
function filters(){const input=$("[data-lender-filter]"),rate=$("[data-rate-filter]");const filter=()=>$$('[data-lender-row]').forEach(row=>row.hidden=!((row.dataset.lender||"").includes((input?.value||"").toLowerCase())&&(rate?.value==="all"||+row.dataset.rate<=+rate.value)));input?.addEventListener("input",filter);rate?.addEventListener("change",filter);filter();const search=$("[data-resource-search]");search?.addEventListener("input",()=>$$('[data-resource-card]').forEach(c=>c.classList.toggle("hidden",!c.innerText.toLowerCase().includes(search.value.toLowerCase()))))}
function faq(){ $$(".faq-button").forEach(b=>b.addEventListener("click",()=>{const item=b.closest(".faq-item"),open=item.classList.toggle("open");b.setAttribute("aria-expanded",String(open));const icon=$("span",b);if(icon)icon.textContent=open?"−":"+"}))}
function documents(){const box=$("[data-document-checklist]");if(!box)return;const items=$$("input",box),bar=$("[data-document-progress]",box),label=$("[data-document-label]",box);const run=()=>{const done=items.filter(x=>x.checked).length;bar.style.width=`${done/items.length*100}%`;label.textContent=`${done} of ${items.length} ready`;store("hlsp_documents",items.map(x=>({name:x.value,done:x.checked})));};items.forEach(x=>x.addEventListener("change",run));const saved=load("hlsp_documents");items.forEach(x=>x.checked=saved.find(y=>y.name===x.value)?.done||false);run()}
function tracking(){event("page_view",{utm_source:new URLSearchParams(location.search).get("utm_source")||"direct",utm_medium:new URLSearchParams(location.search).get("utm_medium")||"none",utm_campaign:new URLSearchParams(location.search).get("utm_campaign")||"none"});$$('a[href^="tel:"]').forEach(a=>a.addEventListener("click",()=>event("call_clicked")));$$('a[href*="wa.me"]').forEach(a=>a.addEventListener("click",()=>event("whatsapp_clicked")))}
function admin(){const events=load("hlsp_events"),leads=load("hlsp_leads"),rows=$("[data-admin-leads]");$$('[data-event-count]').forEach(x=>x.textContent=events.filter(e=>e.event===x.dataset.eventCount).length);$$('[data-lead-count]').forEach(x=>x.textContent=x.dataset.leadCount==="all"?leads.length:leads.filter(l=>l.status===x.dataset.leadCount).length);if(rows){rows.innerHTML=leads.length?leads.map(l=>`<tr><td>${l.id}</td><td>${l.name||"-"}</td><td>${l.city||"-"}</td><td><span class="badge">${l.status}</span></td><td>${l.source||"direct"}</td><td>${new Date(l.created).toLocaleDateString("en-IN")}</td></tr>`).join(""):`<tr><td colspan="6">No local lead records yet.</td></tr>`;$("[data-admin-search]")?.addEventListener("input",e=>$$('tbody tr',rows).forEach(r=>r.hidden=!r.innerText.toLowerCase().includes(e.target.value.toLowerCase())))}}

function creativeMotion(){const rail=document.querySelector('.journey-rail');if(rail){const links=[...rail.querySelectorAll('a')];links.forEach((a,i)=>{a.style.transitionDelay=`${i*25}ms`;a.addEventListener('mouseenter',()=>links.forEach((x,j)=>x.classList.toggle('is-near',Math.abs(j-i)===1)))})}document.querySelectorAll('.card,.hero-card,.form-card').forEach(el=>el.addEventListener('mousemove',e=>{const r=el.getBoundingClientRect();el.style.setProperty('--mx',`${((e.clientX-r.left)/r.width*100).toFixed(1)}%`);el.style.setProperty('--my',`${((e.clientY-r.top)/r.height*100).toFixed(1)}%`)}));}

function initHomeLoanApp(){bindNextLevelFeatures();bindSignalHeader();navigation();reveal();calculator();leadForms();eligibility();matching();transferTopup();filters();faq();documents();tracking();admin();creativeMotion()};if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',initHomeLoanApp)}else{initHomeLoanApp()}})();
